name: Auto Commits

on:
    schedule:
        - cron: "0 0,6,12,18 * * *" # 4 times daily
    workflow_dispatch:

jobs:
    commit:
        permissions:
            contents: write
        runs-on: ubuntu-latest

        steps:
            - name: Checkout Repo
              uses: actions/checkout@v4
              with:
                  persist-credentials: true

            - name: Generate commits
              run: |
                  git config user.name "$GITHUB_ACTOR"
                  git config user.email "${GITHUB_ACTOR}@users.noreply.github.com"

                  echo "Auto commit - $(date -u +"%Y-%m-%d %H:%M:%S UTC")" >> activity.log
                  git add activity.log
                  if git commit -m "Auto commit $(date -u +"%Y-%m-%d %H:%M:%S UTC")"; then
                      git push
                  else
                      echo "No changes to commit"
                  fi
